# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
#
#IP="172.28.128.111"
#HOSTNAME="fedoraconfig"
FEDORA_VM_BOX="fedora/30-cloud-base"
FEDORA_VERSION="30"

Vagrant.configure(2) do |config|

  config.vm.define "Fedora VM" do |fedoraconfig|
    #fedoraconfig.vm.box = "fedora/30-cloud-base"
    fedoraconfig.vm.box = FEDORA_VM_BOX
    ##fedoraconfig.vm.box_version = "1546371671"
    fedoraconfig.vm.network "private_network", type: "dhcp", bridge: "Vagrant"
    #fedoraconfig.vm.synced_folder ".", "/home/vagrant/sync", disabled: true
    fedoraconfig.vm.provision "shell", path: "provision.sh", args: ["172.28.128.111","fedoraconfig"]
    fedoraconfig.vm.network "forwarded_port", guest: 22, host: 2202
  end

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Fedora " + FEDORA_VERSION
    vb.cpus = 1
    vb.memory = 2048
    vb.customize ["modifyvm", :id, "--groups", '/Tierra_Fedora_Kickstart']
  end
end
